-- https://school.programmers.co.kr/learn/courses/30/lessons/132204#qna

SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A
INNER JOIN PATIENT P
ON A.PT_NO = P.PT_NO
INNER JOIN DOCTOR D
ON A.MDDR_ID = D.DR_ID
WHERE DATE(A.APNT_YMD) = '2022-04-13'
      AND A.APNT_CNCL_YN = 'N' AND A.APNT_CNCL_YMD IS NULL AND A.MCDP_CD = 'CS'
ORDER BY A.APNT_YMD ASC