-- https://school.programmers.co.kr/learn/courses/30/lessons/131117

SELECT FOOD_PRODUCT.PRODUCT_ID, FOOD_PRODUCT.PRODUCT_NAME, (FOOD_PRODUCT.PRICE * B.TOTAL_AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT
INNER JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT
    FROM FOOD_ORDER
    WHERE MONTH(PRODUCE_DATE) = 5
    GROUP BY PRODUCT_ID
) AS B
ON FOOD_PRODUCT.PRODUCT_ID = B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FOOD_PRODUCT.PRODUCT_ID ASC
