-- https://school.programmers.co.kr/learn/courses/30/lessons/131124#qna

SELECT MEMBER_PROFILE.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE
INNER JOIN (
    SELECT MEMBER_ID, REVIEW_TEXT, REVIEW_DATE
    FROM REST_REVIEW
    WHERE MEMBER_ID = (
        SELECT MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(*) DESC
        LIMIT 1
    )
) AS B
ON MEMBER_PROFILE.MEMBER_ID = B.MEMBER_ID
ORDER BY REVIEW_DATE ASC, B.REVIEW_TEXT ASC