-- https://school.programmers.co.kr/learn/courses/30/lessons/133027

SELECT FIRST_HALF.FLAVOR
FROM FIRST_HALF
INNER JOIN (
    SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) AS B
ON FIRST_HALF.FLAVOR = B.FLAVOR
ORDER BY (FIRST_HALF.TOTAL_ORDER + B.TOTAL_ORDER) DESC
LIMIT 3