-- https://school.programmers.co.kr/learn/courses/30/lessons/157339#qna

SELECT c.CAR_ID, c.CAR_TYPE,
       c.DAILY_FEE * 30 * (100 - p.DISCOUNT_RATE) DIV 100 AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
ON c.CAR_ID = h.CAR_ID
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
ON c.CAR_TYPE = p.CAR_TYPE
WHERE c.CAR_TYPE IN ('세단', 'SUV') AND p.DURATION_TYPE LIKE '30일%'
GROUP BY c.CAR_ID
HAVING SUM(IF(TIMESTAMPDIFF(day,'2022-11-01 00:00:00',h.END_DATE) * 
              TIMESTAMPDIFF(day,'2022-11-30 00:00:00',h.START_DATE) <= 0, 1, 0)
       ) = 0
       AND FEE BETWEEN 50000 AND 2000000
ORDER BY FEE DESC, c.CAR_TYPE ASC, c.CAR_ID DESC